name: Release

on:
  push:
    branches:
      - main
    tags:
      - 'v*.*'  # Match semantic version tags like v1.2

jobs:
  test:
    uses: ./.github/workflows/test.yml  # Runs your test suite via reusable workflow

  release:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: sbt

      - name: Setup sbt launcher
        uses: sbt/setup-sbt@v1

      - name: Build JAR
        run: sbt assembly

      - name: Release to GitHub
        uses: softprops/action-gh-release@v2
        if: github.ref_type == 'tag'
        with:
          files: target/scala-*/func-rail*.jar
          generate_release_notes: true
