name: Scala Job Template

on:
  workflow_call:
    inputs:
      task:
        description: "Comando sbt da eseguire"
        required: true
        type: string

jobs:
  scala-job:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin
          cache: sbt

      - uses: sbt/setup-sbt@v1

      - name: Run ${{ inputs.task }}
        run: ${{ inputs.task }}
