name: Test

on:
  workflow_call:
  push:
  pull_request:

jobs:
  test-scala:
    uses: ./.github/workflows/scala-job-template.yml
    with:
      task: "sbt test"

  scala-fix:
    uses: ./.github/workflows/scala-job-template.yml
    with:
      task: "sbt scalafixAll"
  
  check-format:
    uses: ./.github/workflows/scala-job-template.yml
    with:
      task: "sbt scalafmtCheckAll"
